config/routes.rb
Rails.application.routes.draw do
  resources :open_houses
  resources :media
  resources :rooms
  resources :offices
  resources :agents
  resources :listings
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/agent.rb
class Agent < ActiveRecord::Base
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	scope :orange, -> { where(county_or_parish:'Orange') }

	ACT = 'ACT'
	PNC = 'PNC'
	SLD = 'SLD'
	LSE = 'LSE'


	self.primary_key = 'matrix_unique_id'
	# QUERY = "(Status=|ACT),(PropertyType=|RES),(CountyOrParish=| Orange,Osceola)"
	# #counties = "Alachua,Baker,Bay,Bradford,Brevard,Broward,Calhoun,Charlotte,Citrus,Clay,Collier,Columbia,Dade,DeSoto,Dixie,Duval,Escambia,Flagler,Franklin,Gadsen,Gilchrist,Glades,Gulf,Hamilton,Hardee,Hendry,Hernando,Highlands,Hillsborough,Holmes,IndianRiver,Jackson,Jefferson,Lafayette,Lake,Lee,Leon,Levy,Liberty,Madison,Manatee,Marion,Monroe,Nassau,Okaloosa,Okeechobee,Orange,Osceola,Other,OutofArea,PalmBeach,Pasco,Pinellas,Polk,Putnam,Sarasota,Seminole,StJohns,Union,Volusia"
	#  CreateRetsService.new.call
	# 	def active
	# 	 $client.login
	# 	$client.find :all, {
	# 		             search_type: 'Property',
	# 	               class: 'Listing',
	# 	               query: "#{QUERY}"
	# 	                 }
	# 	end


	# attr_reader :status
	#
	# [:active, :inactive, :pending].each do |method|
	# 	define_method "#{method}?" do
	# 		status == User.const_get(method.upcase)
	# 	end
	# end


end

app/models/medium.rb
class Medium < ActiveRecord::Base
end

app/models/office.rb
class Office < ActiveRecord::Base
end

app/models/open_house.rb
class OpenHouse < ActiveRecord::Base
end

app/models/room.rb
class Room < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/agents_controller.rb
class AgentsController < InheritedResources::Base

  private

    def agent_params
      params.require(:agent).permit()
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < InheritedResources::Base

  private

    def listing_params
      params.require(:listing).permit()
    end
end

app/controllers/media_controller.rb
class MediaController < InheritedResources::Base

  private

    def medium_params
      params.require(:medium).permit()
    end
end

app/controllers/offices_controller.rb
class OfficesController < InheritedResources::Base

  private

    def office_params
      params.require(:office).permit()
    end
end

app/controllers/rooms_controller.rb
class RoomsController < InheritedResources::Base

  private

    def room_params
      params.require(:room).permit()
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/open_houses_helper.rb
module OpenHousesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/media/_form.html.erb
<%= simple_form_for(@medium) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/media/edit.html.erb
<h1>Editing Medium</h1>

<%= render 'form' %>

<%= link_to 'Show', @medium %> |
<%= link_to 'Back', media_path %>

app/views/media/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Media</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @media.each do |medium| %>
      <tr>
        <td><%= link_to 'Show', medium %></td>
        <td><%= link_to 'Edit', edit_medium_path(medium) %></td>
        <td><%= link_to 'Destroy', medium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medium', new_medium_path %>

app/views/media/new.html.erb
<h1>New Medium</h1>

<%= render 'form' %>

<%= link_to 'Back', media_path %>

app/views/media/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_medium_path(@medium) %> |
<%= link_to 'Back', media_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>